import type { LineInput } from "@/lib/money";
export type Row = {
  id: string;
  name?: string;
  legalName?: string;
  tradeName?: string;
  ruc?: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  notes?: string;
  active?: boolean;
  pricingMode?: "FIXED" | "PER_UNIT";
  stock?: number;
  sessions?: number;
  nextAppointment?: string | null;
  sku?: string;
  category?: string;
  type?: string;
  price?: string;
  unit?: string;
  taxId?: string | null;
  tax?: { id: string; name: string; rate: string };
  rate?: string;
  description?: string;
  documentNumber?: string;
  date?: string;
  dueDate?: string | null;
  currency?: string;
  exchangeRate?: string;
  status?: string;
  discountRate?: string;
  subtotal?: string;
  discountTotal?: string;
  taxTotal?: string;
  total?: string;
  amountPaid?: string;
  balanceDue?: string;
  terms?: string;
  customerId?: string;
  customer?: Row;
  customerSnapshot?: Record<string, string>;
  companySnapshot?: Record<string, string>;
  items?: (LineInput & {
    id: string;
    sessionsTotal?: number;
    sessionsUsed?: number;
    subtotal: string;
    discount: string;
    tax: string;
    total: string;
  })[];
  invoice?: Row | null;
  invoices?: Row[];
  quotes?: Row[];
  advances?: Row[];
  payments?: Row[];
  payment?: Row;
  receipt?: Row | null;
  amount?: string;
  paymentDate?: string;
  method?: string;
  reference?: string;
  account?: string;
  invoiceId?: string;
  balanceRemaining?: string;
  voidedAt?: string | null;
  createdAt?: string;
  role?: string;
  user?: {
    id: string;
    name: string;
    email: string | null;
    username?: string | null;
    active: boolean;
  };
  action?: string;
  timestamp?: string;
  entityType?: string;
  entityId?: string;
  metadata?: unknown;
};
export type CompanyView = {
  id: string;
  name: string;
  tradeName: string;
  ruc: string;
  logo: string;
  address: string;
  phone: string;
  email: string;
  settings: {
    primaryCurrency: "NIO" | "USD";
    secondaryCurrency: "NIO" | "USD";
    exchangeRate: string;
    invoicePrefix: string;
    quotePrefix: string;
    receiptPrefix: string;
    nextInvoice: number;
    nextQuote: number;
    nextReceipt: number;
    bankInfo: string;
    terms: string;
    notes: string;
    dateFormat: string;
  };
};
export type Options = {
  customers: Row[];
  products: Row[];
  taxes: Row[];
  company: CompanyView;
};
export type Analytics = {
  currency: string;
  start: string;
  end: string;
  sales: string;
  collected: string;
  receivable: string;
  invoiceCount: number;
  customerCount: number;
  overdueCount: number;
  days: { days: number; total: string }[];
  chart: { date: string; total: number }[];
  recent: Row[];
  selected: Row[];
  received: Row[];
  receivables: Row[];
  overdue: Row[];
  topCustomers: { name: string; total: string }[];
  topProducts: { name: string; total: string; quantity: string }[];
  taxes: { rate: string; total: string }[];
};
